export const categoryData = [
    "Food",
  "Transportation",
  "Housing",
  "Utilities",
  "Entertainment",
  "Healthcare",
  "Education",
  "Shopping",
  "Travel",
  "Insurance",
  "Savings",
  "Investments",
  "Salary",
  "Freelance",
  "Rental Income",
  "Side Gig",
  "Gifts",
  "Interest",
  "Other"
]